local addon, engine = ...
engine[1] = {} -- S, functions, constants, variables
engine[2] = {} -- L, localization
engine[3] = {} -- DB

SunUI = engine
local SunUI = LibStub("AceAddon-3.0"):NewAddon("SunUI")
local S, L, DB, _, C = unpack(select(2, ...))
local _G =_G
MoveHandle = {}
--全局设置
local Media = "Interface\\Addons\\SunUI\\media\\"
DB.dummy = function() return end
DB.zone = GetLocale()
DB.level = UnitLevel("player")
DB.MyClass = select(2, UnitClass("player"))
DB.PlayerName = select(1, UnitName("player"))
DB.MyClassColor = RAID_CLASS_COLORS[DB.MyClass]
DB.Font = GameFontNormal:GetFont()
DB.Solid = Media.."solid"
DB.Button = Media.."Button"
DB.GlowTex = Media.."glowTex"
DB.Statusbar2 = Media.."statusbar7"
DB.Statusbar = "Interface\\Buttons\\WHITE8x8" --Media.."dM3"
DB.bgFile = "Interface\\Tooltips\\UI-Tooltip-Background"
DB.edgetex = 	"Interface\\Tooltips\\UI-Tooltip-Border"
DB.aurobackdrop = "Interface\\ChatFrame\\ChatFrameBackground"
DB.onepx = "Interface\\Buttons\\WHITE8x8"
DB.Warning = Media.."Warning.mp3"
DB.MyRealm = GetRealmName()
DB.FontSize = select(2, GameFontNormal:GetFont())