local S, _, L, DB = unpack(SunUI)
local Module = LibStub("AceAddon-3.0"):GetAddon("Core"):NewModule("calculator")
function Module:OnInitialize()
function calc(arg1)
	if arg1=="" then 
		Calc_OpenFrame()
	else
		local x,y=string.find(arg1,"%p?%d*%p?%d*")
		num1 = string.sub(arg1,x,y)
		local h,k=string.find(arg1,"%a*",y+2)
		fun  = string.sub(arg1,h,k)
		local a,z=string.find(arg1,"%p?%d*%p?%d*",k+2)
		num2 = string.sub(arg1,a,z)

		if fun=="plus" then print(num1.." + "..num2.." = "..tonumber(num1)+tonumber(num2)) CalcText = tonumber(num1)+tonumber(num2)
		elseif fun=="minus" then print(num1.." - "..num2.." = "..tonumber(num1)-tonumber(num2)) CalcText = tonumber(num1)-tonumber(num2)
		elseif fun=="times" or fun=="*" then print(num1.." x "..num2.." = "..tonumber(num1)*tonumber(num2)) CalcText = tonumber(num1)*tonumber(num2)
		elseif fun=="divided by" or fun=="divide" then print(num1.." / "..num2.." = "..tonumber(num1)/tonumber(num2)) CalcText = tonumber(num1)/tonumber(num2)
		elseif fun=="caret" or fun=="power" then print(num1.." ^ "..num2.." = "..tonumber(num1)^tonumber(num2)) CalcText = tonumber(num1)^tonumber(num2)
		elseif fun=="root"then print(num2.."th root of "..num1.." = "..tonumber(num1)^(1/tonumber(num2))) CalcText = tonumber(num1)^(1/tonumber(num2))
		end
	end
end

function Calc_OpenFrame()
	if Windowshown==nil then 
		Windowshown="true"

		CalcMainWindow = CreateFrame("Frame",nil,UIParent)
		CalcMainWindow:Width(265)
		CalcMainWindow:Height(207)
		CalcMainWindow:Point("CENTER",UIParent,"CENTER",140,75)
		CalcMainWindow:EnableMouse(true)
		CalcMainWindow:SetMovable(true)
		CalcMainWindow:SetScript("OnMouseDown",function() CalcMainWindow:StartMoving() end)
		CalcMainWindow:SetScript("OnMouseUp",function() CalcMainWindow:StopMovingOrSizing() end)
		CalcMainWindow:SetFrameLevel(1)
		CalcMainWindow:CreateShadow("Background")
		
		
		CalcMainWindowText = CalcMainWindow:CreateFontString(nil,nil,"GameFontHighlight")
		CalcMainWindowText:Point("TOPLEFT",CalcMainWindow,"TOPLEFT",7,-7)
		CalcMainWindowText:SetTextColor(1,1,0)
		CalcMainWindowText:SetText("SunUI Calculator")

		CalcCloseButton = CreateFrame("Button",nil,CalcMainWindow)
		CalcCloseButton:Width(20)
		CalcCloseButton:Height(20)

		CalcCloseButton:SetBackdropColor(1,0,0)
		CalcCloseButton:Point("TOPRIGHT",CalcMainWindow,"TOPRIGHT",-7,-7)
		CalcCloseButton:EnableMouse(true)
		CalcCloseButton:SetScript("OnMouseUp",function() CalcMainWindow:Hide() CalcEditBox:SetText("") end)
		CalcCloseButton:SetFrameLevel(2)
		CalcCloseButton.text = S.MakeFontString(CalcCloseButton, 10)
		CalcCloseButton.text:SetText("X")
		CalcCloseButton.text:Point("CENTER", 3, 0)
		CalcCloseButton.text:SetTextColor(1, 1, 1)
		S.Reskin(CalcCloseButton)
		
		CalcEditBox = CreateFrame("EditBox","CalcEditBox",CalcMainWindow,"InputBoxTemplate")
		CalcEditBox:Height(30)
		CalcEditBox:Width(250)
		CalcEditBox:Point("TOP",CalcMainWindow,"TOP",3,-37)
		CalcEditBox:SetAutoFocus(false)
		CalcEditBox:SetJustifyH("RIGHT")
		CalcEditBox:SetTextInsets(5,5,0,0)
		CalcEditBox:SetScript("OnEnterPressed",function() calc(CalcEditBox:GetText()) CalcEditBox:SetText(CalcText) end)
	elseif Windowshown=="true" then 
		CalcMainWindow:Hide()
		Windowshown="false"
	elseif Windowshown=="false" then 
		CalcMainWindow:Show()
		Windowshown="true"
	end
Calculator_Buttons()
end

function Calculator_Buttons()
	zero = CreateFrame("Button",nil,CalcMainWindow)
	zero:Height(20)
	zero:Width(40)
	zerotext = zero:CreateFontString(nil,nil,"GameFontHighlightLarge")
	zerotext:SetTextColor(1,1,1)
	zerotext:SetText("0")
	zerotext:Point("CENTER",zero,"CENTER")
	zero:EnableMouse(true)
	zero:Point("BOTTOMLEFT",CalcMainWindow,"BOTTOMLEFT",20,20)
	zero:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."0" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(zero)
	S.MakeBG(zero, 0)
	
	one = CreateFrame("Button",nil,CalcMainWindow)
	one:Height(20)
	one:Width(40)
	onetext = one:CreateFontString(nil,nil,"GameFontHighlightLarge")
	onetext:SetTextColor(1,1,1)
	onetext:SetText("1")
	onetext:Point("CENTER",one,"CENTER")
	one:EnableMouse(true)
	one:Point("BOTTOMLEFT",zero,"TOPLEFT",0,5)
	one:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."1" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(one)
	S.MakeBG(one, 0)
	
	two = CreateFrame("Button",nil,CalcMainWindow)
	two:Height(20)
	two:Width(40)
	two:SetBackdropColor(1,1,1)
	twotext = two:CreateFontString(nil,nil,"GameFontHighlightLarge")
	twotext:SetTextColor(1,1,1)
	twotext:SetText("2")
	twotext:Point("CENTER",two,"CENTER")
	two:EnableMouse(true)
	two:Point("LEFT",one,"RIGHT",5,0)
	two:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."2" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(two)
	S.MakeBG(two, 0)
	
	three = CreateFrame("Button",nil,CalcMainWindow)
	three:Height(20)
	three:Width(40)
	threetext = three:CreateFontString(nil,nil,"GameFontHighlightLarge")
	threetext:SetTextColor(1,1,1)
	threetext:SetText("3")
	threetext:Point("CENTER",three,"CENTER")
	three:EnableMouse(true)
	three:Point("LEFT",two,"RIGHT",5,0)
	three:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."3" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(three)
	S.MakeBG(three, 0)
	
	four = CreateFrame("Button",nil,CalcMainWindow)
	four:Height(20)
	four:Width(40)
	fourtext = four:CreateFontString(nil,nil,"GameFontHighlightLarge")
	fourtext:SetTextColor(1,1,1)
	fourtext:SetText("4")
	fourtext:Point("CENTER",four,"CENTER")
	four:EnableMouse(true)
	four:Point("BOTTOM",one,"TOP",0,5)
	four:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."4" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(four)
	S.MakeBG(four, 0)
	
	five = CreateFrame("Button",nil,CalcMainWindow)
	five:Height(20)
	five:Width(40)
	fivetext = five:CreateFontString(nil,nil,"GameFontHighlightLarge")
	fivetext:SetTextColor(1,1,1)
	fivetext:SetText("5")
	fivetext:Point("CENTER",five,"CENTER")
	five:EnableMouse(true)
	five:Point("LEFT",four,"RIGHT",5,0)
	five:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."5" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(five)
	S.MakeBG(five, 0)
	
	six = CreateFrame("Button",nil,CalcMainWindow)
	six:Height(20)
	six:Width(40)
	sixtext = six:CreateFontString(nil,nil,"GameFontHighlightLarge")
	sixtext:SetTextColor(1,1,1)
	sixtext:SetText("6")
	sixtext:Point("CENTER",six,"CENTER")
	six:EnableMouse(true)
	six:Point("LEFT",five,"RIGHT",5,0)
	six:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."6" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(six)
	S.MakeBG(six, 0)
	
	seven = CreateFrame("Button",nil,CalcMainWindow)
	seven:Height(20)
	seven:Width(40)
	seventext = seven:CreateFontString(nil,nil,"GameFontHighlightLarge")
	seventext:SetTextColor(1,1,1)
	seventext:SetText("7")
	seventext:Point("CENTER",seven,"CENTER")
	seven:EnableMouse(true)
	seven:Point("BOTTOM",four,"TOP",0,5)
	seven:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."7" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(seven)
	S.MakeBG(seven, 0)
	
	eight = CreateFrame("Button",nil,CalcMainWindow)
	eight:Height(20)
	eight:Width(40)
	eighttext = eight:CreateFontString(nil,nil,"GameFontHighlightLarge")
	eighttext:SetTextColor(1,1,1)
	eighttext:SetText("8")
	eighttext:Point("CENTER",eight,"CENTER")
	eight:EnableMouse(true)
	eight:Point("LEFT",seven,"RIGHT",5,0)
	eight:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."8" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(eight)
	S.MakeBG(eight, 0)
	
	nine = CreateFrame("Button",nil,CalcMainWindow)
	nine:Height(20)
	nine:Width(40)
	ninetext = nine:CreateFontString(nil,nil,"GameFontHighlightLarge")
	ninetext:SetTextColor(1,1,1)
	ninetext:SetText("9")
	ninetext:Point("CENTER",nine,"CENTER")
	nine:EnableMouse(true)
	nine:Point("LEFT",eight,"RIGHT",5,0)
	nine:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().."9" CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(nine)
	S.MakeBG(nine, 0)
	
	sign = CreateFrame("Button",nil,CalcMainWindow)
	sign:Height(20)
	sign:Width(40)
	signtext = sign:CreateFontString(nil,nil,"GameFontHighlightLarge")
	signtext:SetTextColor(1,1,1)
	signtext:SetText("+/-")
	signtext:Point("CENTER",sign,"CENTER")
	sign:EnableMouse(true)
	sign:Point("LEFT",zero,"RIGHT",5,0)
	sign:SetScript("OnMouseUp",function() local teststring = string.sub(CalcEditBox:GetText(),1,1) if teststring=="-" then CalcText = string.sub(CalcEditBox:GetText(),2) CalcEditBox:SetText(CalcText) else CalcText = "-"..CalcEditBox:GetText() CalcEditBox:SetText(CalcText) end end)

	S.Reskin(sign)
	S.MakeBG(sign, 0)
	
	point = CreateFrame("Button",nil,CalcMainWindow)
	point:Height(20)
	point:Width(40)
	pointtext = point:CreateFontString(nil,nil,"GameFontHighlightLarge")
	pointtext:SetTextColor(1,1,1)
	pointtext:SetText(".")
	pointtext:Point("CENTER",point,"CENTER")
	point:EnableMouse(true)
	point:Point("LEFT",sign,"RIGHT",5,0)
	point:SetScript("OnMouseUp",function() CalcEditBox:SetText(CalcEditBox:GetText()..".") end)
	S.Reskin(point)
	S.MakeBG(point, 0)
	
	plus = CreateFrame("Button",nil,CalcMainWindow)
	plus:Height(20)
	plus:Width(40)
	plustext = plus:CreateFontString(nil,nil,"GameFontHighlightLarge")
	plustext:SetTextColor(1,1,1)
	plustext:SetText("+")
	plustext:Point("CENTER",plus,"CENTER")
	plus:EnableMouse(true)
	plus:Point("LEFT",point,"RIGHT",5,0)
	plus:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().." plus " CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(plus)
	S.MakeBG(plus, 0)
	
	minus = CreateFrame("Button",nil,CalcMainWindow)
	minus:Height(20)
	minus:Width(40)
	minustext = minus:CreateFontString(nil,nil,"GameFontHighlightLarge")
	minustext:SetTextColor(1,1,1)
	minustext:SetText("-")
	minustext:Point("CENTER",minus,"CENTER")
	minus:EnableMouse(true)
	minus:Point("BOTTOM",plus,"TOP",0,5)
	minus:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().." minus " CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(minus)
	S.MakeBG(minus, 0)
	
	times = CreateFrame("Button",nil,CalcMainWindow)
	times:Height(20)
	times:Width(40)
	timestext = times:CreateFontString(nil,nil,"GameFontHighlightLarge")
	timestext:SetTextColor(1,1,1)
	timestext:SetText("*")
	timestext:Point("CENTER",times,"CENTER")
	times:EnableMouse(true)
	times:Point("BOTTOM",minus,"TOP",0,5)
	times:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().." times " CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(times)
	S.MakeBG(times, 0)
	
	divide = CreateFrame("Button",nil,CalcMainWindow)
	divide:Height(20)
	divide:Width(40)
	dividetext = divide:CreateFontString(nil,nil,"GameFontHighlightLarge")
	dividetext:SetTextColor(1,1,1)
	dividetext:SetText("/")
	dividetext:Point("CENTER",divide,"CENTER")
	divide:EnableMouse(true)
	divide:Point("BOTTOM",times,"TOP",0,5)
	divide:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().." divide " CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(divide)
	S.MakeBG(divide, 0)
	
	equals = CreateFrame("Button",nil,CalcMainWindow)
	equals:Height(20)
	equals:Width(40)
	equalstext = equals:CreateFontString(nil,nil,"GameFontHighlightLarge")
	equalstext:SetTextColor(1,1,1)
	equalstext:SetText("=")
	equalstext:Point("CENTER",equals,"CENTER")
	equals:EnableMouse(true)
	equals:Point("LEFT",plus,"RIGHT",5,0)
	equals:SetScript("OnMouseUp",function() calc(CalcEditBox:GetText()) CalcEditBox:SetText(CalcText) end)
	S.Reskin(equals)
	S.MakeBG(equals, 0)
	
	recip = CreateFrame("Button",nil,CalcMainWindow)
	recip:Height(20)
	recip:Width(40)
	reciptext = recip:CreateFontString(nil,nil,"GameFontHighlightLarge")
	reciptext:SetTextColor(1,1,1)
	reciptext:SetText("1/x")
	reciptext:Point("CENTER",recip,"CENTER")
	recip:EnableMouse(true)
	recip:Point("BOTTOM",equals,"TOP",0,5)
	recip:SetScript("OnMouseUp",function() local x,y=string.find(CalcEditBox:GetText(),"%p?%d*%p?%d*") CalcEditBox:SetText(1/tonumber(string.sub(CalcEditBox:GetText(),x,y))) end)
	S.Reskin(recip)
	S.MakeBG(recip, 0)
	
	power = CreateFrame("Button",nil,CalcMainWindow)
	power:Height(20)
	power:Width(40)
	powertext = power:CreateFontString(nil,nil,"GameFontHighlightLarge")
	powertext:SetTextColor(1,1,1)
	powertext:SetText("^")
	powertext:Point("CENTER",power,"CENTER")
	power:EnableMouse(true)
	power:Point("BOTTOM",recip,"TOP",0,5)
	power:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().." power " CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(power)
	S.MakeBG(power, 0)
	
	root = CreateFrame("Button",nil,CalcMainWindow)
	root:Height(20)
	root:Width(40)
	roottext = root:CreateFontString(nil,nil,"GameFontHighlightLarge")
	roottext:SetTextColor(1,1,1)
	roottext:SetText("rt")
	roottext:Point("CENTER",root,"CENTER")
	root:EnableMouse(true)
	root:Point("BOTTOM",power,"TOP",0,5)
	root:SetScript("OnMouseUp",function() CalcText = CalcEditBox:GetText().." root " CalcEditBox:SetText(CalcText) CalcEditBox:SetFocus() CalcEditBox:SetCursorPosition(9999999) end)
	S.Reskin(root)
	S.MakeBG(root, 0)
end

SlashCmdList["CALCULATOR"] = calc
SLASH_CALCULATOR1 = "/calc"
SLASH_CALCULATOR2 = "/jsq"
end