if not IsAddOnLoaded("AuctionLite") then return end
local S, C, L, DB = unpack(select(2, ...))
local _
S.Reskin(BuyScanButton)
S.Reskin(BuySearchButton)
S.Reskin(BuySummaryButton, true)
BuySummaryButton:SetNormalTexture("Interface\\Buttons\\UI-SpellbookIcon-PrevPage-Up")
S.Reskin(BuyBidButton)
S.Reskin(BuyBuyoutButton)
S.Reskin(BuyCancelAuctionButton)
S.Reskin(SellCreateAuctionButton)
S.ReskinRadio(SellShortAuctionButton)
S.ReskinRadio(SellMediumAuctionButton)
S.ReskinRadio(SellLongAuctionButton)
S.ReskinRadio(SellPerItemButton)
S.ReskinRadio(SellPerStackButton)